stages:
  save_and_split_data:
    cmd: python src/save_and_split_data.py --config=params.yaml
    deps: 
    - src/retrieve_data.py
    - src/save_and_split_data.py
    outs:
    - artifacts/clean_data.csv
    - artifacts/train.csv
    - artifacts/test.csv

  data_transformation:
    cmd: python src/data_transformation.py --config=params.yaml
    deps: 
      - src/retrieve_data.py
      - src/save_and_split_data.py
      - src/data_transformation.py
    outs:
      - artifacts/preprocessor.pkl
  
  model_trainer:
    cmd: python src/model_training.py --config=params.yaml
    deps: 
      - src/retrieve_data.py
      - src/save_and_split_data.py
      - src/data_transformation.py
      - src/model_training.py
    metrics:
      - reports/best_model_scores.json:
          cache: false
    outs:
      - models/model.pkl