stages:
  save_and_split_data:
    cmd: python src/save_and_split_data.py --config=params.yaml
    deps: 
    - src/retrieve_data.py
    - src/save_and_split_data.py
    outs:
    - artifacts/clean_data.csv
    - artifacts/train.csv
    - artifacts/test.csv

  