project:
  project_name: adult_census_income_prediction
  target_col: income

data_source:
  mongodb_url: mongodb+srv://sunny:{password}@cluster0.gswp8ro.mongodb.net/?retryWrites=true&w=majority
  database : census
  collection: clean_data

save_and_split_data:
  raw_dataset: artifacts/clean_data.csv
  train_path: artifacts/train.csv
  test_path: artifacts/test.csv
  test_size: 0.20
  random_state: 12

data_transformation:
  preprocessor_path: artifacts/preprocessor.pkl

model: 
  saved_model: models/model.pkl