project:
  project_name: adult_census_income_prediction
  target_col: income

data_source:
  mongodb_url: mongodb+srv://{username}:{password}@cluster0.gswp8ro.mongodb.net/?retryWrites=true&w=majority
  database : census
  collection: clean_data

save_and_split_data:
  raw_dataset: artifacts/clean_data.csv
  train_path: artifacts/train.csv
  test_path: artifacts/test.csv
  test_size: 0.20
  random_state: 12

data_transformation:
  preprocessor_path: artifacts/preprocessor.pkl
  numerical_cols: ['age', 'capital-gain', 'capital-loss', 'hours-per-week',
       'marital_status_group', 'native_group', 'workclass_group', 'race_group',
       'sex_group']
  categorical_cols: ["education_group"]
  categorical_cols1: ['occupation_group','Relationship_Group']
  edu_category: ['Primary', 'Secondary', 'High School Graduation', 'Some College', "Associate's Degree",
                "Bachelor's Degree", "Master's Degree", "Professional Degree", 'Doctorate Degree']
model: 
  saved_model: models/model.pkl

reports:
  scores: reports/best_model_scores.json