channels:
- conda-forge
dependencies:
- python=3.8.17
- pip<=23.1.2
- pip:
  - mlflow==2.7.1
  - cloudpickle==2.2.1
  - numpy==1.24.4
  - packaging==23.1
  - pandas==2.0.3
  - psutil==5.9.0
  - pyyaml==6.0
  - scikit-learn==1.3.0
  - scipy==1.10.1
  - xgboost==1.7.6
name: mlflow-env
